apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: promise-name
spec:
  dependencies: []
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: PLURAL.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: KIND
        plural: PLURAL
        singular: SINGULAR
      scope: Namespaced
      versions:
        - name: v1alpha1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
              type: object
              properties:
                spec:
                  type: object
                  required:
                    - prop1
                  properties:
                    prop1:
                      description: A property to be configured
                      type: string
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: instance-configure
            namespace: default
          spec:
            containers:
              - image: ghcr.io/syntasso/kratix-marketplace/namespace-configure-pipeline:v0.1.0
                name: namespace-configure-pipeline


